apiVersion: v1
kind: Service
metadata:
  name: orbit-api
  labels:
    app.kubernetes.io/name: orbit-api
    app.kubernetes.io/part-of: orbit
    {{- include "orbit.commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
  selector:
    app.kubernetes.io/name: orbit-api
    app.kubernetes.io/part-of: orbit
