apiVersion: v1
kind: ConfigMap
metadata:
  name: orbit-config
  labels:
    app.kubernetes.io/name: orbit-api
    app.kubernetes.io/part-of: orbit
    {{- include "orbit.commonLabels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
