{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: orbit-postgres-secret
  labels:
    app.kubernetes.io/name: orbit-postgres
    app.kubernetes.io/part-of: orbit
    {{- include "orbit.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
