apiVersion: v1
kind: Secret
metadata:
  name: orbit-db-secret
  labels:
    app.kubernetes.io/name: orbit-api
    app.kubernetes.io/part-of: orbit
    {{- include "orbit.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  ORBIT_DB_HOST: {{ .Values.db.host | quote }}
  ORBIT_DB_PORT: {{ .Values.db.port | quote }}
  ORBIT_DB_NAME: {{ .Values.db.name | quote }}
  ORBIT_DB_USER: {{ .Values.db.user | quote }}
  ORBIT_DB_PASSWORD: {{ .Values.db.password | quote }}
  ORBIT_DB_SSLMODE: {{ .Values.db.sslmode | quote }}
