{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orbit.apiServiceAccountName" . }}
  labels:
    app.kubernetes.io/name: orbit-api
    app.kubernetes.io/part-of: orbit
    {{- include "orbit.commonLabels" . | nindent 4 }}
{{- end }}
